version: 2
jobs:
  build:
    working_directory: ~/epublib-build
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: epublib-build-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: epublib-build-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_test_results:
          paths:
            - epublib-core/target/surefire-reports
            - epublib-tools/target/surefire-reports
